app = "bakame-elevenlabs-mcp"
primary_region = "fra"

[build]

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8000"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
