name: Deploy to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'bakame-backend/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Backend to Fly.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        working-directory: ./bakame-backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
